### ISSUE TITLE
Property binding for complex Polymer components doesn't work

### ISSUE THREAD

**Issue by simonovdenis** [vaadin/angular2-polymer#156]
Assuming I have Angular 2 component, which contains following html(angular-component.html) and uses Predix polymer 1.0 component [px-datetime-picker](https://www.predix-ui.com/#/elements/datetime/px-datetime-picker) (internally it contains other polymer components like  [px-datetime-field](https://www.predix-ui.com/#/elements/datetime/px-datetime-field)):
`<table>
        <tbody>
        <tr valign="middle">
          <td style="vertical-align: middle;">Reference Day</td>
          <td>
            <px-datetime-picker
                                [date-time]="referenceDay"
                                date-format="DD.MM.YYYY"
                                time-format="hh:mm A"
                                hide-time="true"
                                show-time-zone="none"
                                time-zone="UTC"
            ></px-datetime-picker>
          </td>
        </tr>
        </tbody>
      </table>`
referenceDay property in Angular is defined as follows:
`@Component({
  selector: 'angular-component',
  templateUrl: 'angular-component.html',
  styleUrls: ['../../sass/angular-component.scss'],
  providers: [],
  entryComponents: []
})
export class MyAngularComponent {
  referenceDay: string;

  constructor() {
    this.referenceDay = moment().utc().startOf('day').clone().subtract(7, 'days').toISOString();
  }
  ngOnInit() {
    console.log('init ' + this.referenceDay);
  }
...`
When I'm trying to set referenceDay to some value in Angular component programmatically - for example in constructor(expecting  it to automatically reflect to polymer px-datetime-picker component) - it is not passed to polymer((inner px-datetime-field contains previous value - current date), while in angular it is set to new value(I'm checking it in ngOnInit - it is correct value = today - 7 days).

**Comment by hotforfeature** [comment]
Angular `[ ]` syntax binds to properties by default, not attributes. You're binding to `datepicker['date-time'] = referenceDay` which probably isn't the correct property name. Try

```
<px-datetime-picker [dateTime]="referenceDay"
```

or 

```
<px-datetime-picker [attr.date-time]="referenceDay"
```

**Comment by simonovdenis** [comment]
You're genious. Thanks!
